# Generated by Django 2.1a1 on 2018-05-21 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('board_id', models.CharField(max_length=250)),
                ('start_columns_str', models.CharField(blank=True, max_length=250, null=True)),
                ('end_columns_str', models.CharField(blank=True, max_length=250, null=True)),
                ('trello_user_key', models.CharField(max_length=250)),
                ('trello_user_token', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('choice_text', models.CharField(max_length=200)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('column_id', models.CharField(max_length=250, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('label_id', models.CharField(max_length=250, unique=True)),
                ('color', models.CharField(max_length=200)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('column', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.Column')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(to='pyrellowebapp.Label'),
        ),
        migrations.AddField(
            model_name='card',
            name='transactions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.Transaction'),
        ),
    ]
