# Generated by Django 2.1a1 on 2018-05-21 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0002_auto_20180521_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.Column'),
        ),
    ]
