# Generated by Django 2.1a1 on 2018-05-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0007_endleadtimecolumn_startleadtimecolumn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endleadtimecolumn',
            name='board',
        ),
        migrations.RemoveField(
            model_name='endleadtimecolumn',
            name='column',
        ),
        migrations.RemoveField(
            model_name='startleadtimecolumn',
            name='board',
        ),
        migrations.RemoveField(
            model_name='startleadtimecolumn',
            name='column',
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='column',
            name='importance_order',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='column',
            name='leadtime_period',
            field=models.CharField(choices=[('Start', 'Pode representar o início do Leadtime'), ('End', 'Pode representar o fim do Leadtime'), ('None', 'Não considerar nem como início nem fim')], default='None', max_length=5),
        ),
        migrations.DeleteModel(
            name='EndLeadTimeColumn',
        ),
        migrations.DeleteModel(
            name='StartLeadTimeColumn',
        ),
    ]
