# Generated by Django 2.0.5 on 2018-06-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0013_graphdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_type',
            field=models.CharField(choices=[('trello', 'Trello'), ('jira', 'Jira')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='board',
            name='jira_server_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='card_type',
            field=models.CharField(choices=[('value', 'Valor'), ('bug', 'Bug'), ('improvement', 'Melhorias'), ('ops', 'Ops'), ('others', 'Outros')], default='others', max_length=40),
        ),
    ]
