# Generated by Django 2.0.5 on 2018-06-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0014_auto_20180608_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_id',
            field=models.CharField(max_length=250),
        ),
    ]
