# Generated by Django 2.0.5 on 2018-06-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0015_auto_20180609_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='column_id',
            field=models.CharField(max_length=250),
        ),
    ]
