# Generated by Django 2.0.5 on 2018-06-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0016_auto_20180609_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartCFD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_columns', models.CharField(max_length=250)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.Board')),
            ],
        ),
        migrations.CreateModel(
            name='ChartCFDData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('day', models.DateField()),
                ('chartcfd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.ChartCFD')),
            ],
        ),
    ]
