# Generated by Django 2.0.5 on 2018-06-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0017_chartcfd_chartcfddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartThroughput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('card_type', models.CharField(choices=[('value', 'Valor'), ('bug', 'Bug'), ('improvement', 'Melhorias'), ('ops', 'Ops'), ('others', 'Outros')], max_length=40)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='column',
            name='leadtime_period',
            field=models.CharField(choices=[('Start', 'Início do Leadtime'), ('End', 'Fim do Leadtime'), ('None', 'Indiferente')], default='None', max_length=5),
        ),
    ]
