# Generated by Django 2.0.5 on 2018-06-14 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0018_auto_20180614_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartthroughput',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='chartthroughput',
            name='total',
        ),
        migrations.AddField(
            model_name='chartthroughput',
            name='board',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.Board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartthroughput',
            name='data',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartthroughput',
            name='week_label',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
