# Generated by Django 2.0.5 on 2018-06-15 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0019_auto_20180614_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartLeadtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('data', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.Card')),
            ],
        ),
    ]
