# Generated by Django 2.0.5 on 2018-06-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0020_chartleadtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartleadtime',
            name='leadtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
