# Generated by Django 2.0.5 on 2018-06-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0023_card_end_date_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='end_date_cache',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
