# Generated by Django 2.0.5 on 2018-07-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0027_script_delete_leadtime_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='filter_by_label',
            field=models.CharField(default='', max_length=250),
        ),
    ]
