# Generated by Django 2.0.5 on 2018-07-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0028_board_filter_by_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='filter_by_label',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
