# Generated by Django 2.0.5 on 2018-07-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0029_auto_20180710_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartleadtime',
            name='service_class',
            field=models.CharField(default='standard', max_length=30),
        ),
        migrations.AlterField(
            model_name='label',
            name='service_class',
            field=models.CharField(choices=[('expedite', 'Expedite'), ('standard', 'Tarefa padrão'), ('fixed', 'Data fixa'), ('intangible', 'Intangível'), ('none', 'Não é classe de serviço')], default='none', max_length=30),
        ),
    ]
