# Generated by Django 2.0.5 on 2018-07-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0030_auto_20180718_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartleadtime',
            name='card_type',
            field=models.CharField(default='others', max_length=30),
        ),
    ]
