# Generated by Django 2.0.5 on 2018-05-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0008_auto_20180524_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='board',
            name='end_columns_str',
        ),
        migrations.RemoveField(
            model_name='board',
            name='start_columns_str',
        ),
    ]
