# Generated by Django 2.0.5 on 2018-05-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0009_auto_20180525_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='service_class',
            field=models.CharField(choices=[('expedite', 'Expedite'), ('standart', 'Tarefa padrão'), ('fixed', 'Data fixa'), ('intangible', 'Intangível'), ('none', 'Não é classe de serviço')], default='none', max_length=30),
        ),
    ]
