# Generated by Django 2.0.5 on 2018-05-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0011_label_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='board_position',
            field=models.FloatField(default=0),
        ),
    ]
