# Generated by Django 2.0.5 on 2018-05-30 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0012_column_board_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.CharField(choices=[('Leadtime', 'Leadtime'), ('Throughput', 'Throughput'), ('CFD', 'CFD'), ('Histogram', 'Leadtime Histogram'), ('90Percentil', '90 Percentil Leadtime'), ('ThroughputMean', 'Média Throughput'), ('ThroughputMedian', 'Mediana Throughput')], max_length=100)),
                ('data', models.TextField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.Board')),
            ],
        ),
    ]
