# Generated by Django 2.1a1 on 2018-05-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0005_auto_20180521_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
