# Generated by Django 2.1a1 on 2018-05-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyrellowebapp', '0006_auto_20180521_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndLeadTimeColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.Board')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.Column')),
            ],
        ),
        migrations.CreateModel(
            name='StartLeadTimeColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.Board')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyrellowebapp.Column')),
            ],
        ),
    ]
